name: jsonata_flutter
description: A Flutter implementation of JSONata query and transformation language
version: 1.0.1
homepage: https://github.com/hakanmertb/jsonata_flutter
publish_to: https://pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_js: ^0.8.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0